# Authorization: Bearer 
### images Index
GET http://localhost:3000/images.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjgwMTk5NjJ9.8uWpNykfOZec6wyaLWww8O-SlWl0IYiI8_MnNZrPTH0

### images Create
POST http://localhost:3000/images.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjgwMTk5NjJ9.8uWpNykfOZec6wyaLWww8O-SlWl0IYiI8_MnNZrPTH0

{
  "image_url": "test.png",
  "name": "test name",
  "description": "test description",
  "tags": ["rodeo", "zeus"]
}


### images Show
GET http://localhost:3000/images/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjgwMTk5NjJ9.8uWpNykfOZec6wyaLWww8O-SlWl0IYiI8_MnNZrPTH0

### images Update
PATCH http://localhost:3000/images/3.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjgwMTk5NjJ9.8uWpNykfOZec6wyaLWww8O-SlWl0IYiI8_MnNZrPTH0

{
"image_url": "new.png",
"name": "new name",
"description": "new description"
}

### images Destroy
DELETE http://localhost:3000/images/3.json

#######################################

### tags Index
GET http://localhost:3000/tags.json

### tags Create
POST http://localhost:3000/tags.json
Content-Type: application/json

{
"name": "test tag"
}

### tags Show
GET http://localhost:3000/tags/9.json

### tags Update
PATCH http://localhost:3000/tags/9.json
Content-Type: application/json

{
"name": "new tag"
}

### tags Destroy
DELETE http://localhost:3000/tags/9.json

###########################################

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}